import { it,expect,beforeEach,afterEach } from 'vitest';import { promises as fs } from 'node:fs';import path from 'node:path';import os from 'node:os';import { WebSocket } from 'ws';
import { ProfileStore } from '../electron/store';import { startOutputServer } from '../electron/server';import { IDLE,profileSchema } from '../src/shared/types';
let dir:string,store:ProfileStore,server:Awaited<ReturnType<typeof startOutputServer>>|undefined;
beforeEach(async()=>{dir=await fs.mkdtemp(path.join(os.tmpdir(),'luma-test-'));await fs.mkdir(path.join(dir,'dist','assets'),{recursive:true});await fs.writeFile(path.join(dir,'dist','overlay.html'),'<canvas></canvas>');await fs.writeFile(path.join(dir,'dist','index.html'),'Studio');store=new ProfileStore(path.join(dir,'data'),path.join(dir,'dist'));await store.init();});
afterEach(async()=>{await server?.close();server=undefined;await fs.rm(dir,{recursive:true,force:true});});
it('round-trips profiles and relative PNG assets after relocation',async()=>{const p=await store.create('Test');const png=Buffer.from([137,80,78,71,13,10,26,10,1]);const ref=await store.importBytes(png);p.poses['center.neutral']=ref;await store.save(p);expect(await store.load(p.id)).toEqual(p);const relocated=path.join(dir,'relocated');await fs.cp(store.root,relocated,{recursive:true});const next=new ProfileStore(relocated,path.join(dir,'dist'));expect(await next.load(p.id)).toEqual(p);expect(await fs.readFile(next.assetPath(ref))).toEqual(png);});
it('rejects path traversal and incompatible schemas',async()=>{expect(()=>store.assetPath('../../preferences.json')).toThrow();const p=await store.create('Test');expect(()=>profileSchema.parse({...p,version:99})).toThrow();await expect(store.importBytes(Buffer.from('bad PNG'))).rejects.toThrow();});
it('protects output, studio and avatar files, and disallows writes',async()=>{const p=await store.create('Test');server=await startOutputServer(path.join(dir,'dist'),store,'secret','studio',p,0);expect((await fetch(server.url+'/overlay.html')).status).toBe(403);expect((await fetch(server.url+'/overlay.html?token=secret')).status).toBe(200);expect((await fetch(server.url+'/index.html?token=secret')).status).toBe(403);expect((await fetch(server.url+'/index.html?studio=studio')).status).toBe(200);expect((await fetch(server.url+'/preferences.json?token=secret')).status).toBe(404);expect((await fetch(server.url+'/avatar/assets/'+ 'a'.repeat(64)+'.png?token=secret')).status).toBe(404);expect((await fetch(server.url+'/overlay.html?token=secret',{method:'POST'})).status).toBe(405);});
it('sends initial state, publishes movement, and reconnects with current state',async()=>{server=await startOutputServer(path.join(dir,'dist'),store,'secret','studio',await store.create('Test'),0);const url=server.url.replace('http:','ws:')+'/stream?token=secret';const ws=new WebSocket(url);const first=await new Promise<any>(r=>ws.once('message',d=>r(JSON.parse(d.toString()))));expect(first.profile.name).toBe('Test');const next=new Promise<any>(r=>ws.once('message',d=>r(JSON.parse(d.toString()))));server.publish({...IDLE,mouth:.7,talking:true});expect((await next).state.talking).toBe(true);ws.close();const reconnected=new WebSocket(url);const state=await new Promise<any>(r=>reconnected.once('message',d=>r(JSON.parse(d.toString()))));expect(state.state.mouth).toBe(.7);reconnected.close();});
it('rejects unauthorized websocket and client control messages',async()=>{server=await startOutputServer(path.join(dir,'dist'),store,'secret','studio',await store.create('Test'),0);const bad=new WebSocket(server.url.replace('http:','ws:')+'/stream?token=wrong');await new Promise<void>(r=>bad.on('error',()=>r()));const ws=new WebSocket(server.url.replace('http:','ws:')+'/stream?token=secret');await new Promise<void>(r=>ws.once('open',()=>r()));const closed=new Promise<number>(r=>ws.once('close',r));ws.send('change avatar');expect(await closed).toBe(1008);});
it('keeps camera diagnostics and landmarks out of the OBS output packet',async()=>{
  server=await startOutputServer(path.join(dir,'dist'),store,'secret','studio',await store.create('Test'),0);
  const ws=new WebSocket(server.url.replace('http:','ws:')+'/stream?token=secret');
  await new Promise<void>(r=>ws.once('message',()=>r()));
  const next=new Promise<any>(r=>ws.once('message',d=>r(JSON.parse(d.toString()))));
  server.publish({...IDLE,points:[.5,.5],audioLevel:.2,webcam:'raw'} as typeof IDLE);
  const packet=await next;expect(Object.keys(packet).sort()).toEqual(['profile','state']);
  expect(packet.state).toEqual(IDLE);ws.close();
});
