import { useEffect,useRef,useState } from 'react';
import { AnimationState,AvatarProfile,IDLE,Signals,TrackingFrame,ZERO } from '../shared/types';
import { MotionEngine } from '../shared/engine';
export function useTracking(profile:AvatarProfile,onCalibration:(neutral:Signals)=>void,onError:(error:string)=>void){
  const video=useRef<HTMLVideoElement|null>(null),worker=useRef<Worker|null>(null),stream=useRef<MediaStream|null>(null),audio=useRef<{stream:MediaStream;ctx:AudioContext;analyser:AnalyserNode;data:Float32Array<ArrayBuffer>}|null>(null);
  const frame=useRef<TrackingFrame>({...ZERO,timestamp:0,status:'paused',audioActive:false,micEnabled:false}),state=useRef<AnimationState>({...IDLE}),engine=useRef(new MotionEngine()),current=useRef(profile),callback=useRef(onCalibration),errorCallback=useRef(onError);
  current.current=profile;callback.current=onCalibration;errorCallback.current=onError;
  const [running,setRunning]=useState(false),[starting,setStarting]=useState(false),[mic,setMic]=useState(false),[status,setStatus]=useState('Camera off'),[fps,setFps]=useState(0),[calibrationProgress,setCalibrationProgress]=useState<number|null>(null),[display,setDisplay]=useState<AnimationState>({...IDLE});
  const active=useRef(false),busy=useRef(false),ready=useRef(false),duration=useRef(0),received=useRef(0),calibration=useRef<{sum:Signals;elapsed:number;count:number;last:number}|null>(null),generation=useRef(0),startPending=useRef(false);
  const audioGeneration=useRef(0);
  function stop(){generation.current++;active.current=false;worker.current?.terminate();worker.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(video.current)video.current.srcObject=null;busy.current=false;ready.current=false;frame.current={...ZERO,timestamp:performance.now(),status:'paused',audioActive:false,micEnabled:false};setRunning(false);setStarting(false);startPending.current=false;setStatus('Camera off');setFps(0);calibration.current=null;setCalibrationProgress(null);stopMic();}
  async function start(deviceId?:string){if(startPending.current)return;stop();startPending.current=true;const gen=generation.current;setStarting(true);setStatus('Loading local tracking model…');try{
    const media=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:640},height:{ideal:480},frameRate:{ideal:30},...(deviceId?{deviceId:{exact:deviceId}}:{})},audio:false});if(gen!==generation.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;media.getVideoTracks()[0].onended=()=>{stop();errorCallback.current('Webcam disconnected. Reconnect it, then start the camera again.');};
    if(!video.current)throw new Error('Camera preview is unavailable.');video.current.srcObject=media;await video.current.play();if(gen!==generation.current)return;
    const w=new Worker('/models/tracker.js');worker.current=w;
    const loadTimer=window.setTimeout(()=>{if(!ready.current&&gen===generation.current){stop();errorCallback.current('Tracking model did not start. Restart Luma and check the bundled model files.');}},45000);
    w.onmessage=({data})=>{if(gen!==generation.current)return;if(data.type==='ready'){clearTimeout(loadTimer);ready.current=true;active.current=true;setRunning(true);setStarting(false);startPending.current=false;frame.current.status='lost';setStatus('Looking for your face');}
      if(data.type==='result'){busy.current=false;duration.current=data.duration;received.current=performance.now();frame.current={...data.frame,audioActive:false,micEnabled:!!audio.current};const cal=calibration.current;if(cal){if(data.frame.status==='tracked'){if(cal.last)cal.elapsed+=Math.min(data.frame.timestamp-cal.last,250);cal.last=data.frame.timestamp;cal.count++;for(const k of Object.keys(ZERO) as (keyof Signals)[])cal.sum[k]+=data.frame[k];setCalibrationProgress(Math.min(100,cal.elapsed/30));if(cal.elapsed>=3000){const neutral={...ZERO};for(const k of Object.keys(ZERO) as (keyof Signals)[])neutral[k]=cal.sum[k]/cal.count;calibration.current=null;setCalibrationProgress(null);callback.current(neutral);engine.current.reset();}}else cal.last=0;}}
      if(data.type==='error'){clearTimeout(loadTimer);stop();errorCallback.current(`Tracking could not run: ${data.message}`);}};
    w.onerror=()=>{if(gen!==generation.current)return;clearTimeout(loadTimer);stop();errorCallback.current('Tracking worker failed. Restart Luma; the local model or WASM files may be missing.');};
    w.postMessage({type:'init',base:location.origin});
  }catch(e){if(gen!==generation.current)return;stop();const name=(e as DOMException).name;errorCallback.current(name==='NotAllowedError'?'Camera access was denied. Enable camera access for desktop apps in Windows Settings, then try again.':name==='NotReadableError'?'The camera is busy. Close other apps using it, then try again.':name==='NotFoundError'?'No webcam was found. Connect a camera and try again.':`Camera could not start: ${(e as Error).message}`);}}
  function stopMic(){audioGeneration.current++;audio.current?.stream.getTracks().forEach(t=>t.stop());void audio.current?.ctx.close();audio.current=null;setMic(false);}
  async function startMic(deviceId?:string){stopMic();const gen=generation.current,agen=audioGeneration.current;let media:MediaStream|undefined,ctx:AudioContext|undefined;try{media=await navigator.mediaDevices.getUserMedia({audio:{...(deviceId?{deviceId:{exact:deviceId}}:{}),echoCancellation:true,noiseSuppression:true},video:false});if(gen!==generation.current||agen!==audioGeneration.current){media.getTracks().forEach(t=>t.stop());return;}ctx=new AudioContext();await ctx.resume();if(gen!==generation.current||agen!==audioGeneration.current){media.getTracks().forEach(t=>t.stop());await ctx.close();return;}const analyser=ctx.createAnalyser();analyser.fftSize=1024;ctx.createMediaStreamSource(media).connect(analyser);audio.current={stream:media,ctx,analyser,data:new Float32Array(analyser.fftSize)};media.getAudioTracks()[0].onended=()=>{stopMic();errorCallback.current('Microphone disconnected. Talking animation is using webcam movement.');};setMic(true);}catch{media?.getTracks().forEach(t=>t.stop());void ctx?.close();if(gen!==generation.current||agen!==audioGeneration.current)return;stopMic();errorCallback.current('Microphone access is unavailable. Webcam-only mouth animation remains available.');}}
  function calibrate(){if(!active.current)return;calibration.current={sum:{...ZERO},elapsed:0,count:0,last:0};setCalibrationProgress(0);}
  function reacquire(){worker.current?.postMessage({type:'reset'});engine.current.reset();}
  useEffect(()=>{let alive=true,raf=0,lastCapture=0,lastUI=0,lastPublish=0,lastAudio=0,lastVideo=-1,captures=0,lastRate=performance.now();
    const tick=async(t:number)=>{if(!alive)return;const a=audio.current;if(a){a.analyser.getFloatTimeDomainData(a.data);const rms=Math.sqrt(a.data.reduce((sum,v)=>sum+v*v,0)/a.data.length);if(rms>current.current.settings.micThreshold)lastAudio=t;}const f={...frame.current,timestamp:t,micEnabled:!!a,audioActive:!!a&&t-lastAudio<160};if(active.current&&t-received.current>Math.max(250,duration.current*2))f.status='lost';state.current=engine.current.step(f,current.current);
      if(t-lastPublish>33){window.desktop?.publish(state.current);lastPublish=t;}if(t-lastUI>100){setDisplay({...state.current});if(active.current)setStatus(f.status==='tracked'?'Face tracked':'Face lost · reacquire if needed');lastUI=t;}
      if(t-lastRate>=1000){setFps(captures);captures=0;lastRate=t;}
      const v=video.current;if(active.current&&ready.current&&!busy.current&&v&&v.readyState>=2&&v.currentTime!==lastVideo&&t-lastCapture>Math.max(33,duration.current*1.2)){lastVideo=v.currentTime;lastCapture=t;busy.current=true;const gen=generation.current;try{const bitmap=await createImageBitmap(v,{resizeWidth:640,resizeHeight:480});if(gen!==generation.current||!worker.current){bitmap.close();}else{worker.current.postMessage({type:'frame',bitmap,timestamp:t},[bitmap]);captures++;}}catch{if(gen===generation.current)busy.current=false;}}
      if(alive)raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);return()=>{alive=false;cancelAnimationFrame(raf);stop();};
  },[]);
  return {video,state,display,running,starting,mic,status,fps,calibrationProgress,start,stop,startMic,stopMic,calibrate,reacquire};
}
