const { _electron }=require(process.env.SPROUT_PLAYWRIGHT||'playwright');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),sharp=require('sharp');
(async()=>{
 const workspace=path.resolve('../..'),fixtures=path.join(workspace,'work','facing-fixtures'),data=process.env.SPROUT_SMOKE_DATA_DIR||path.join(workspace,'work','smoke-facing');await fs.mkdir(fixtures,{recursive:true});
 const colors={center:[40,150,210],left:[210,50,50],right:[50,180,80],combined:[220,190,40]};
 for(const [name,rgb]of Object.entries(colors))await sharp({create:{width:1024,height:1024,channels:4,background:{r:rgb[0],g:rgb[1],b:rgb[2],alpha:1}}}).png().toFile(path.join(fixtures,name+'.png'));
 const launch=()=>_electron.launch({executablePath:process.env.SPROUT_EXECUTABLE||require('electron'),args:process.env.SPROUT_EXECUTABLE?['--no-sandbox']:['.','--no-sandbox'],env:{...process.env,SPROUT_TEST_MODE:'1',SPROUT_DATA_DIR:data},timeout:30000});let app,overlay,page;const errors=[];
 try{
 app=await launch();page=await app.firstWindow();page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));await page.getByRole('heading',{name:'Bring a little character.'}).waitFor();const config=await page.evaluate(()=>window.desktop.config());if(config.serverWarning)await page.getByRole('button',{name:'Dismiss error'}).click();
 const waitColor=(p,selector,name)=>p.waitForFunction(({selector,rgb})=>{const c=document.querySelector(selector);if(!c)return false;const a=c.getContext('2d').getImageData(c.width/2,c.height/2,1,1).data;return rgb.every((v,i)=>Math.abs(v-a[i])<2);},{selector,rgb:colors[name]},{timeout:20000});
 const direction=async d=>{await page.locator('.facing-tabs').getByRole('button',{name:new RegExp('^'+d)}).click();};
 const importFile=async(button,name)=>{await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({filePaths:[file],canceled:false});},path.join(fixtures,name+'.png'));await page.getByRole('button',{name:button,exact:true}).click();};
 await page.getByRole('button',{name:'Artwork & rig'}).click();await page.getByRole('button',{name:'PNG poses',exact:true}).click();
 await importFile('Replace PNG','center');await page.waitForFunction(async()=>(await window.desktop.config()).active.poses['center.neutral'].startsWith('assets/'));await waitColor(page,'.stage canvas','center');
 console.log('Importing side artwork');await direction('Left');await importFile('Replace PNG','left');await page.getByLabel('Expression',{exact:true}).selectOption('smile');await page.getByLabel('Variant',{exact:true}).selectOption('.talk.blink');await importFile('Assign PNG','combined');
 await direction('Right');await page.getByLabel('Expression',{exact:true}).selectOption('neutral');await page.getByLabel('Variant',{exact:true}).selectOption('');await importFile('Replace PNG','right');
 await page.getByRole('switch',{name:'Directional sprite states',exact:true}).click();await page.waitForFunction(async()=>(await window.desktop.config()).active.settings.directionalStates===false);
 console.log('Opening OBS');const next=app.waitForEvent('window');await app.evaluate(async({BrowserWindow},url)=>{const w=new BrowserWindow({width:1024,height:1024,useContentSize:true,show:false,webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true}});await w.loadURL(url);},config.outputUrl);overlay=await next;await overlay.setViewportSize({width:1024,height:1024});await waitColor(overlay,'canvas','center');
 console.log('Checking local preview');await direction('Left');await page.getByLabel('Expression',{exact:true}).selectOption('smile');await page.getByLabel('Variant',{exact:true}).selectOption('.talk.blink');await page.getByRole('switch',{name:'Preview facing artwork',exact:true}).click();await waitColor(page,'.stage canvas','combined');await waitColor(overlay,'canvas','center');
 await page.getByRole('switch',{name:'Preview facing artwork',exact:true}).click();await page.getByRole('switch',{name:'Directional sprite states',exact:true}).click();
 await page.evaluate(()=>{
  window.__facingSignals={yaw:35,mouth:0,smile:0,blinkLeft:0,blinkRight:0};
  const canvas=document.createElement('canvas');canvas.width=640;canvas.height=480;const ctx=canvas.getContext('2d');let pulse=0;window.__facingTimer=setInterval(()=>{ctx.fillStyle=`rgb(${pulse++%255},80,80)`;ctx.fillRect(0,0,640,480);},33);
  navigator.mediaDevices.getUserMedia=async c=>{if(c.video)return canvas.captureStream(30);throw new Error('No test microphone');};
  window.Worker=class{onmessage=null;terminate(){this.dead=true;}postMessage(data){if(data.type==='init')setTimeout(()=>this.onmessage?.({data:{type:'ready',connections:[]}}),0);if(data.type==='frame'){data.bitmap.close();setTimeout(()=>{if(!this.dead)this.onmessage?.({data:{type:'result',duration:5,frame:{timestamp:data.timestamp,status:'tracked',yaw:0,pitch:0,roll:0,x:0,y:0,mouth:0,smile:0,brow:0,blinkLeft:0,blinkRight:0,...window.__facingSignals}}});},5);}}};
 });
 await app.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('/index.html'))?.show();});
 console.log('Checking synthetic yaw');await page.getByRole('button',{name:'Start camera',exact:true}).click();await page.getByText('Tracking live',{exact:true}).waitFor();await waitColor(page,'.stage canvas','left');await waitColor(overlay,'canvas','left');
 await page.evaluate(()=>{window.__facingSignals={yaw:35,mouth:1,smile:1,blinkLeft:1,blinkRight:1};});await waitColor(page,'.stage canvas','combined');await waitColor(overlay,'canvas','combined');
 await page.evaluate(()=>{window.__facingSignals.yaw=-35;});await waitColor(page,'.stage canvas','right');await waitColor(overlay,'canvas','right');
 await page.getByRole('switch',{name:'Directional sprite states',exact:true}).click();await page.evaluate(()=>{window.__facingSignals={yaw:-35,mouth:0,smile:0,blinkLeft:0,blinkRight:0};});await waitColor(page,'.stage canvas','center');await waitColor(overlay,'canvas','center');
 await page.getByRole('button',{name:'Pause tracking'}).click();await page.evaluate(()=>clearInterval(window.__facingTimer));
 console.log('Checking layered artwork');await page.getByRole('button',{name:'Layered rig',exact:true}).click();for(const name of ['Body','Eyes','Brows','Mouth'])await page.locator('.layer-row').filter({hasText:new RegExp('^'+name)}).getByTitle('Toggle visibility').click();
 console.log('Importing side artwork');await direction('Left');await importFile('Assign Left Resting PNG','left');await direction('Right');await importFile('Assign Right Resting PNG','right');
 await page.getByRole('switch',{name:'Preview facing artwork',exact:true}).click();await page.getByLabel('Preview expression',{exact:true}).selectOption('neutral');await page.getByLabel('Preview animation',{exact:true}).selectOption('');await waitColor(page,'.stage canvas','right');
 await page.locator('.layer-row').filter({hasText:/^Eyes/}).getByRole('button').first().click();await page.locator('.layer-row').filter({hasText:/^Eyes/}).getByTitle('Toggle visibility').click();
 console.log('Importing side artwork');await direction('Left');await importFile('Assign Left Blinking PNG','combined');await page.getByLabel('Preview animation',{exact:true}).selectOption('.blink');await waitColor(page,'.stage canvas','combined');
 await direction('Right');await importFile('Assign Right Blinking PNG','left');await waitColor(page,'.stage canvas','left');
 await page.getByRole('button',{name:'Save changes'}).click();await page.getByRole('button',{name:'Saved',exact:true}).waitFor();const saved=await page.evaluate(()=>window.desktop.config());assert.equal(saved.active.settings.directionalStates,false);assert(saved.active.layers.find(l=>l.id==='eyes').variants['left.blink']);assert(saved.active.layers.find(l=>l.id==='head').variants['right.neutral']);assert.equal(await page.getByRole('alert').count(),0);
 await page.locator('.toast').waitFor({state:'detached'});await page.screenshot({path:path.join(workspace,'outputs','Sprout-facing-states.png'),fullPage:true});
 assert.equal(await overlay.locator('video').count(),0);await overlay.close();overlay=null;await app.close();app=await launch();page=await app.firstWindow();await page.getByRole('heading',{name:'Bring a little character.'}).waitFor();const reloaded=await page.evaluate(()=>window.desktop.config());assert.deepEqual(reloaded.active,saved.active);assert.deepEqual(errors,[]);
 const result={passed:true,checks:['Native side-state pose assignment','Combined side smile/talk/blink rendering','Synthetic yaw selects left/right in studio and OBS','Centered-only toggle with yaw still active','Artwork preview remains local when states are disabled','Layered side resting and blink variants','Facing banks and toggle survive application restart','No webcam footage in OBS'],pageErrors:errors};await fs.writeFile(path.join(workspace,'work','facing-smoke-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
 }catch(e){if(page)console.log((await page.locator('body').innerText().catch(()=>'(unavailable)')).slice(-3500));throw e;}finally{await app?.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
